# Generated by Django 3.2.5 on 2021-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('cvss2_nvd_base_score', models.CharField(max_length=50)),
                ('cvss2_nvd_vector', models.CharField(max_length=50)),
                ('cvss3_nvd_base_score', models.CharField(max_length=50)),
                ('cvss3_nvd_vector', models.CharField(max_length=50)),
                ('refer', models.CharField(max_length=50)),
                ('cwe_id', models.CharField(max_length=50)),
                ('cwe_name', models.CharField(max_length=50)),
                ('cpe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nvd',
            },
        ),
    ]
