# Generated by Django 2.2.24 on 2021-08-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaks', '0002_auto_20210823_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leak',
        ),
    ]
