server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leak?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minidle: 3
    maxActive: 18
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    filters: stat,wall,log4j

#  security:
#    user:
#      name: admin
#      password: admin

  data:
    mongodb:
      uri: mongodb://zh:zhanghe@127.0.0.1:27017/vuln
#      uri: mongodb://zh:zhanghe@10.0.3.31:27017/vuln

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

