server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leak?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
#    password: VpFr8XrFsRUGic
    password: vuln
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minidle: 3
    maxActive: 18
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    filters: stat,wall,log4j

#  security:
#    user:
#      name: admin
#      password: admin

  data:
    mongodb:
#      uri: mongodb://tf:wn3e8d4d@10.0.3.37:27017/vuln
      uri: mongodb://admin:123456@127.0.0.1:27017/vuln
    option:
      min-connection-per-host: 0
      max-connection-per-host: 100
      threads-allowed-to-block-for-connection-multiplier: 5
      server-selection-timeout: 30000
      max-wait-time: 120000
      max-connection-idle-time: 0
      max-connection-life-time: 0
      connect-timeout: 10000
      socket-timeout: 0
      socket-keep-alive: false
      ssl-enabled: false
      ssl-invalid-host-name-allowed: false
      always-use-m-beans: false
      heartbeat-socket-timeout: 20000
      heartbeat-connect-timeout: 20000
      min-heartbeat-frequency: 500
      heartbeat-frequency: 10000
      local-threshold: 15
    neo4j:
      database: neo4j
#      database: demo

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: tfsecneo4j
#      password: tfsecneo4j

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

